### ISSUE TITLE
Build Package Dependencies out of date

### ISSUE THREAD

**Issue by majick777** [elmsln/wp-plugin-webcomponents#3]
When I did `yarn install`, a number of @lrnwebcomponents dependencies from the `package.json` came up saying those versions didn't exist (2.0.1) and asking to pick a different version. I changed those to 2.0.10 which seemed to be the latest, but as of testing some didn't have a 2.0.10 version yet - app-datepicker (2.0.9), media-gallery (2.0.4)... (I'm not sure why those 2.0.1 versions would not be there no longer? Of course updating the `package.json` versions will fix this, but curious also as to why those previous versions seem to have "dissappeared." )

Frustratingly, selecting the version manually for these did not do anything, yarn just sits there and does not continue, so I had to edit the `package.json` a few times with trial and error to bump to the right version and start the build again... after getting through that, I am told yarn cannot find "a suitable version" for @webcomponentsjs and schema-utils... I picked the latest for each and then it installed...

But I got further stuck at the `polymer build` step because I get (for @lrnwebcomponents/haxcms-elements): Error: file not found with singular glob: /wp-content/webcomponents/node_modules/@lrnwebcomponents/haxcms-elements/lib/haxcms-backend-demo.js

At which point I will have to leave it for now as I'm out of spare time...

Also, I know this is more with Polymer and NPM but when I first tried to install Polymer with  `npm install -g polymer-cli` it failed to install to `/usr/local/bin/node_modules/polymer-cli/node_modules/wd/build` (which doesn't seem/feel right?) - but `yarn global add polymer-cli` worked fine (note: on Ubuntu 16 server.)

**Comment by btopro** [comment]
thank you for running through this. if I include prebuilt as the default setting and then point people over to the actual repo to do legit contribution to it. It'll be hard to keep package json's and dependencies correct in these non-traditional "CMS" centric repos (my drupal integrations have the same issue).

**Comment by btopro** [comment]
When we get through the current sprint this will go into the Experience Zero clean up.

**Comment by btopro** [comment]
this should be cleaned up / more sustainable
